resolver: lts-14.7

extra-deps:
- happy-1.19.12

packages:
- '.'
- 'patched-deps/Cabal-3.0.0.0'

nix:
   enable: false
   packages:
   - autoconf
   - automake
   - gcc
   - git
   - ncurses
   - perl
